#!/usr/bin/env python3
import xml.etree.ElementTree as ET
from pathlib import Path

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""

EN = {
    "Language": "Language",
    "Login": "Login",
    "Logout": "Logout",
    "User": "User",
    "Close": "Close",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Save": "Save",
    "Search": "Search",
    "Actions": "Actions",
    "Yes": "Yes",
    "No": "No",
    "Unknown": "Unknown",
    "Export": "Export",
    "Edit": "Edit",
    "Module": "Module",
    "Total": "Total",
    "Scheduled": "Scheduled",
    "Active": "Active",
    "Records": "Records",
    "ToggleMenu": "Toggle menu",
    "HospitalManagementSystem": "Hospital Management System",
    "MediSphereBrand": "MediSphere",
    "FooterCopyright": "© {0} MediSphere — Hospital Management System",
    "Nav_Dashboard": "Dashboard",
    "Nav_Patients": "Patients",
    "Nav_AddPatient": "Add A Patient",
    "Nav_Appointments": "Appointments",
    "Nav_Prescriptions": "Prescriptions",
    "Nav_AddPrescription": "Add Prescription",
    "Nav_Reports": "Reports",
    "Nav_ReportTypes": "Report Types",
    "Nav_GenerateReport": "Generate A Report",
    "Nav_AdminSettings": "Administrator Settings",
    "Home_Title": "Home",
    "Home_Heading": "MediSphere — Hospital Management System",
    "Home_Description": "A modern hospital management platform built with your clinic's future in mind. Streamline patients, appointments, prescriptions, and reports in one place.",
    "Home_SignIn": "Sign in to get started",
    "Home_HealthcareAlt": "Healthcare professionals",
    "Dashboard_Title": "Dashboard",
    "Dashboard_Welcome": "Welcome to MediSphere",
    "Dashboard_Overview": "Hospital overview — select a module below or use the sidebar.",
    "Dashboard_PatientsCount": "{0} Patients",
    "Dashboard_AppointmentsCount": "{0} Appointments",
    "Dashboard_PrescriptionsCount": "{0} Prescriptions",
    "Dashboard_ReportsCount": "{0} Reports",
    "Dashboard_QuickStart": "Quick start",
    "Dashboard_QuickStartText": "Use the sidebar to navigate between Patients, Appointments, Prescriptions, and Reports. Administrator Settings is available for users with the Administrator role.",
    "Patients_Title": "Patients",
    "Patients_Subtitle": "Search and manage patient records.",
    "Patients_SearchPlaceholder": "Search patients...",
    "PatientId": "Patient ID",
    "FirstName": "First Name",
    "LastName": "Last Name",
    "MiddleName": "Middle Name",
    "EmailAddress": "Email Address",
    "ContactNumber": "Contact Number",
    "PhoneNumber": "Phone Number",
    "Gender": "Gender",
    "DateOfBirth": "Date Of Birth",
    "TreatmentType": "Treatment Type",
    "AddPatient_Title": "Add A Patient",
    "AddPatient_Subtitle": "Register a new patient in the system.",
    "AddPatient_Button": "Add Patient",
    "UpdatePatient_Title": "Edit Patient",
    "UpdatePatient_Subtitle": "Update patient information.",
    "UpdatePatient_Button": "Update Patient",
    "SelectGender": "Select gender",
    "Gender_Male": "Male",
    "Gender_Female": "Female",
    "Gender_NonBinary": "Non-Binary",
    "Gender_PreferNotToSay": "Prefer not to say",
    "Gender_Custom": "Custom",
    "IsPrivatePatient": "Is not using state healthcare options?",
    "SelectPatient": "-- Select Patient --",
    "PrivateHealthcare": "Private Healthcare",
    "NhsTreatment": "NHS Treatment",
    "Appointments_Title": "Appointments",
    "Appointments_Subtitle": "View and manage the appointment calendar.",
    "AddAppointment": "Add An Appointment",
    "EditAppointment": "Edit Appointment",
    "Topic": "Topic",
    "PatientLabel": "Patient:",
    "StartTime": "Start Time:",
    "EndTime": "End Time:",
    "Notes": "Notes",
    "Status": "Status:",
    "AddAppointmentButton": "Add Appointment",
    "UpdateAppointmentButton": "Update Appointment",
    "DeleteAppointmentButton": "Delete Appointment",
    "Status_Scheduled": "1 - Scheduled",
    "Status_Confirmed": "2 - Confirmed",
    "Status_Arrived": "3 - Arrived",
    "Status_InProgress": "4 - In Progress",
    "Status_Completed": "5 - Completed",
    "Status_Rescheduled": "6 - Rescheduled",
    "Status_Canceled": "7 - Canceled",
    "Status_NoShow": "8 - No-show",
    "Status_Unscheduled": "9 - Unscheduled",
    "Prescriptions_Title": "Prescriptions",
    "Prescriptions_Subtitle": "Manage medication prescriptions for patients.",
    "AddPrescription_Title": "Add Prescription",
    "AddPrescription_Subtitle": "Create a new prescription for a patient.",
    "UpdatePrescription_Title": "Update Prescription",
    "UpdatePrescription_Subtitle": "Edit prescription details.",
    "MedicationName": "Medication Name",
    "Dosage": "Dosage",
    "PaymentNeeded": "Payment Needed",
    "Patient": "Patient",
    "Reports_Title": "Reports",
    "Reports_Subtitle": "Search and manage medical reports.",
    "Reports_SearchPlaceholder": "Search reports...",
    "ReportId": "Report ID",
    "CreatedOn": "Created On",
    "ReportDescription": "Report Description",
    "ReportType": "Report Type",
    "HasBeenPrinted": "Has Report Been Printed?",
    "ReportStatus": "Report Status",
    "ReportStartedBy": "Report Started By Staff member",
    "LastUpdated": "Last Updated",
    "LastUpdatedBy": "Last Updated By",
    "ReportTypes_Title": "Report Types",
    "ReportTypeId": "Report Type ID",
    "TemplateDescription": "Template Description",
    "GenerateReport_Title": "Generate Report",
    "ReportTypeLabel": "Report Type:",
    "ReportTypePlaceholder": "Enter or select a report type",
    "ReportTypeHint": 'Type a new report type or pick a saved template. Use "Save As Template" to reuse a type later.',
    "PatientIdLabel": "Patient ID:",
    "InitialStaffName": "Initial Staff Name:",
    "GenerateReportButton": "Generate Report",
    "SaveAsTemplate": "Save As Template",
    "UpdateReport_Title": "Update Report",
    "UpdateReportButton": "Update Report",
    "ExportReport_Title": "Export Report",
    "ExportReport_Subtitle": "Please enter the file name to use for exporting :)",
    "FileName": "File Name:",
    "ExportToExcel": "Export to Excel",
    "ReportStatus_Created": "1 - Created",
    "ReportStatus_Checking": "2 - Checking",
    "ReportStatus_InProgress": "3 - In Progress",
    "ReportStatus_Completed": "4 - Completed",
    "ReportStatus_Rejected": "5 - Rejected",
    "AdminSettings_Title": "Administrator Settings",
    "AdminSettings_Subtitle": "Manage staff accounts and system users.",
    "RegisterNewUser": "Register a new user",
    "UserSettings": "User Settings",
    "SearchUsersPlaceholder": "Search users...",
    "LockoutUser": "Lockout User",
    "LockoutUserConfirm": "Are you sure you want to lockout this user?",
    "DeleteUser": "Delete User",
    "DeleteUserConfirm": "Are you sure you want to delete the user?",
    "RegisterStaff_Title": "Register Staff Account",
    "UpdateUser_Title": "Update User",
    "SelectRole": "Select a role",
    "Requires2FA": "Requires 2FA?",
    "Requires2FAHint": "Two factor authentication.",
    "Password": "Password",
    "SignUp": "Sign Up",
    "Auth_LogIn": "Log In",
    "Auth_Register": "Register",
    "Account_LoginTitle": "Log in",
    "RememberMe": "Remember Me",
    "ForgotPassword": "Forgot your password?",
    "Account_RegisterTitle": "Register",
    "AcceptedTerms": "I agree to the terms and conditions",
    "Account_LogoutTitle": "Log out",
    "Account_LogoutClick": "Click here to Logout",
    "Account_LogoutSuccess": "You have successfully logged out of the application.",
    "Account_LockoutTitle": "Locked out",
    "Account_LockoutMessage": "This account has been locked. Please try again later or contact the support team for assistance.",
    "Error_Title": "Error.",
    "Error_Message": "An error occurred while processing your request.",
    "RequestId": "Request ID:",
    "LoadingPatients": "Loading patients via API...",
    "LoadingPrescriptions": "Loading prescriptions via API...",
    "LoadingReports": "Loading reports via API...",
    "NoReportType": "No Report type used",
    "ConfirmDeleteAppointment": "Delete this appointment?",
    "ConfirmDeletePrescription": "Delete this prescription?",
    "FailedAddPatient": "Failed to add patient:",
    "FailedUpdatePatient": "Failed to update patient:",
    "FailedLoadPatients": "Failed to load patients:",
    "FailedLoadPatient": "Failed to load patient:",
    "FailedAddAppointment": "Failed to add appointment:",
    "FailedUpdateAppointment": "Failed to update appointment:",
    "FailedDeleteAppointment": "Failed to delete appointment:",
    "FailedLoadAppointment": "Failed to load appointment:",
    "FailedLoadAppointments": "Failed to load appointments:",
    "FailedAddPrescription": "Failed to add prescription:",
    "FailedUpdatePrescription": "Failed to update prescription:",
    "FailedDeletePrescription": "Failed to delete prescription:",
    "FailedLoadPrescriptions": "Failed to load prescriptions:",
    "FailedLoadReports": "Failed to load reports:",
    "InvalidCredentials": "Invalid credentials, Please try again!",
    "AcceptTermsRequired": "Please accept the terms and conditions.",
    "CouldNotCreateReport": "Could not create report.",
    "EnterReportTypeName": "Please enter a report type name before saving as template.",
    "ReportTypeExists": "This report type template already exists.",
    "CouldNotCreateReportType": "Could not create report type.",
    "InvalidFileName": "Please enter a valid file name!",
}

VI = {
    "Language": "Ngôn ngữ",
    "Login": "Đăng nhập",
    "Logout": "Đăng xuất",
    "User": "Người dùng",
    "Close": "Đóng",
    "Cancel": "Hủy",
    "Delete": "Xóa",
    "Save": "Lưu",
    "Search": "Tìm kiếm",
    "Actions": "Thao tác",
    "Yes": "Có",
    "No": "Không",
    "Unknown": "Không rõ",
    "Export": "Xuất",
    "Edit": "Sửa",
    "Module": "Mô-đun",
    "Total": "Tổng",
    "Scheduled": "Đã lên lịch",
    "Active": "Đang hoạt động",
    "Records": "Hồ sơ",
    "ToggleMenu": "Bật/tắt menu",
    "HospitalManagementSystem": "Hệ thống Quản lý Bệnh viện",
    "MediSphereBrand": "MediSphere",
    "FooterCopyright": "© {0} MediSphere — Hệ thống Quản lý Bệnh viện",
    "Nav_Dashboard": "Bảng điều khiển",
    "Nav_Patients": "Bệnh nhân",
    "Nav_AddPatient": "Thêm bệnh nhân",
    "Nav_Appointments": "Lịch hẹn",
    "Nav_Prescriptions": "Đơn thuốc",
    "Nav_AddPrescription": "Thêm đơn thuốc",
    "Nav_Reports": "Báo cáo",
    "Nav_ReportTypes": "Loại báo cáo",
    "Nav_GenerateReport": "Tạo báo cáo",
    "Nav_AdminSettings": "Cài đặt quản trị",
    "Home_Title": "Trang chủ",
    "Home_Heading": "MediSphere — Hệ thống Quản lý Bệnh viện",
    "Home_Description": "Nền tảng quản lý bệnh viện hiện đại, hướng tới tương lai phòng khám của bạn. Quản lý bệnh nhân, lịch hẹn, đơn thuốc và báo cáo tại một nơi.",
    "Home_SignIn": "Đăng nhập để bắt đầu",
    "Home_HealthcareAlt": "Nhân viên y tế",
    "Dashboard_Title": "Bảng điều khiển",
    "Dashboard_Welcome": "Chào mừng đến MediSphere",
    "Dashboard_Overview": "Tổng quan bệnh viện — chọn mô-đun bên dưới hoặc dùng thanh bên.",
    "Dashboard_PatientsCount": "{0} Bệnh nhân",
    "Dashboard_AppointmentsCount": "{0} Lịch hẹn",
    "Dashboard_PrescriptionsCount": "{0} Đơn thuốc",
    "Dashboard_ReportsCount": "{0} Báo cáo",
    "Dashboard_QuickStart": "Bắt đầu nhanh",
    "Dashboard_QuickStartText": "Dùng thanh bên để điều hướng giữa Bệnh nhân, Lịch hẹn, Đơn thuốc và Báo cáo. Cài đặt quản trị dành cho người dùng có vai trò Quản trị viên.",
    "Patients_Title": "Bệnh nhân",
    "Patients_Subtitle": "Tìm kiếm và quản lý hồ sơ bệnh nhân.",
    "Patients_SearchPlaceholder": "Tìm bệnh nhân...",
    "PatientId": "Mã bệnh nhân",
    "FirstName": "Tên",
    "LastName": "Họ",
    "MiddleName": "Tên đệm",
    "EmailAddress": "Địa chỉ email",
    "ContactNumber": "Số liên hệ",
    "PhoneNumber": "Số điện thoại",
    "Gender": "Giới tính",
    "DateOfBirth": "Ngày sinh",
    "TreatmentType": "Loại điều trị",
    "AddPatient_Title": "Thêm bệnh nhân",
    "AddPatient_Subtitle": "Đăng ký bệnh nhân mới trong hệ thống.",
    "AddPatient_Button": "Thêm bệnh nhân",
    "UpdatePatient_Title": "Sửa bệnh nhân",
    "UpdatePatient_Subtitle": "Cập nhật thông tin bệnh nhân.",
    "UpdatePatient_Button": "Cập nhật bệnh nhân",
    "SelectGender": "Chọn giới tính",
    "Gender_Male": "Nam",
    "Gender_Female": "Nữ",
    "Gender_NonBinary": "Phi nhị giới",
    "Gender_PreferNotToSay": "Không muốn nói",
    "Gender_Custom": "Tùy chỉnh",
    "IsPrivatePatient": "Không sử dụng dịch vụ y tế công?",
    "SelectPatient": "-- Chọn bệnh nhân --",
    "PrivateHealthcare": "Y tế tư nhân",
    "NhsTreatment": "Điều trị NHS",
    "Appointments_Title": "Lịch hẹn",
    "Appointments_Subtitle": "Xem và quản lý lịch hẹn.",
    "AddAppointment": "Thêm lịch hẹn",
    "EditAppointment": "Sửa lịch hẹn",
    "Topic": "Chủ đề",
    "PatientLabel": "Bệnh nhân:",
    "StartTime": "Bắt đầu:",
    "EndTime": "Kết thúc:",
    "Notes": "Ghi chú",
    "Status": "Trạng thái:",
    "AddAppointmentButton": "Thêm lịch hẹn",
    "UpdateAppointmentButton": "Cập nhật lịch hẹn",
    "DeleteAppointmentButton": "Xóa lịch hẹn",
    "Status_Scheduled": "1 - Đã lên lịch",
    "Status_Confirmed": "2 - Đã xác nhận",
    "Status_Arrived": "3 - Đã đến",
    "Status_InProgress": "4 - Đang thực hiện",
    "Status_Completed": "5 - Hoàn thành",
    "Status_Rescheduled": "6 - Đã đổi lịch",
    "Status_Canceled": "7 - Đã hủy",
    "Status_NoShow": "8 - Không đến",
    "Status_Unscheduled": "9 - Chưa lên lịch",
    "Prescriptions_Title": "Đơn thuốc",
    "Prescriptions_Subtitle": "Quản lý đơn thuốc cho bệnh nhân.",
    "AddPrescription_Title": "Thêm đơn thuốc",
    "AddPrescription_Subtitle": "Tạo đơn thuốc mới cho bệnh nhân.",
    "UpdatePrescription_Title": "Cập nhật đơn thuốc",
    "UpdatePrescription_Subtitle": "Chỉnh sửa chi tiết đơn thuốc.",
    "MedicationName": "Tên thuốc",
    "Dosage": "Liều lượng",
    "PaymentNeeded": "Cần thanh toán",
    "Patient": "Bệnh nhân",
    "Reports_Title": "Báo cáo",
    "Reports_Subtitle": "Tìm kiếm và quản lý báo cáo y tế.",
    "Reports_SearchPlaceholder": "Tìm báo cáo...",
    "ReportId": "Mã báo cáo",
    "CreatedOn": "Ngày tạo",
    "ReportDescription": "Mô tả báo cáo",
    "ReportType": "Loại báo cáo",
    "HasBeenPrinted": "Đã in báo cáo?",
    "ReportStatus": "Trạng thái báo cáo",
    "ReportStartedBy": "Nhân viên bắt đầu báo cáo",
    "LastUpdated": "Cập nhật lần cuối",
    "LastUpdatedBy": "Người cập nhật",
    "ReportTypes_Title": "Loại báo cáo",
    "ReportTypeId": "Mã loại báo cáo",
    "TemplateDescription": "Mô tả mẫu",
    "GenerateReport_Title": "Tạo báo cáo",
    "ReportTypeLabel": "Loại báo cáo:",
    "ReportTypePlaceholder": "Nhập hoặc chọn loại báo cáo",
    "ReportTypeHint": 'Nhập loại báo cáo mới hoặc chọn mẫu đã lưu. Dùng "Lưu làm mẫu" để tái sử dụng sau.',
    "PatientIdLabel": "Mã bệnh nhân:",
    "InitialStaffName": "Tên nhân viên ban đầu:",
    "GenerateReportButton": "Tạo báo cáo",
    "SaveAsTemplate": "Lưu làm mẫu",
    "UpdateReport_Title": "Cập nhật báo cáo",
    "UpdateReportButton": "Cập nhật báo cáo",
    "ExportReport_Title": "Xuất báo cáo",
    "ExportReport_Subtitle": "Vui lòng nhập tên tệp để xuất :)",
    "FileName": "Tên tệp:",
    "ExportToExcel": "Xuất ra Excel",
    "ReportStatus_Created": "1 - Đã tạo",
    "ReportStatus_Checking": "2 - Đang kiểm tra",
    "ReportStatus_InProgress": "3 - Đang thực hiện",
    "ReportStatus_Completed": "4 - Hoàn thành",
    "ReportStatus_Rejected": "5 - Từ chối",
    "AdminSettings_Title": "Cài đặt quản trị",
    "AdminSettings_Subtitle": "Quản lý tài khoản nhân viên và người dùng hệ thống.",
    "RegisterNewUser": "Đăng ký người dùng mới",
    "UserSettings": "Cài đặt người dùng",
    "SearchUsersPlaceholder": "Tìm người dùng...",
    "LockoutUser": "Khóa người dùng",
    "LockoutUserConfirm": "Bạn có chắc muốn khóa người dùng này?",
    "DeleteUser": "Xóa người dùng",
    "DeleteUserConfirm": "Bạn có chắc muốn xóa người dùng này?",
    "RegisterStaff_Title": "Đăng ký tài khoản nhân viên",
    "UpdateUser_Title": "Cập nhật người dùng",
    "SelectRole": "Chọn vai trò",
    "Requires2FA": "Yêu cầu 2FA?",
    "Requires2FAHint": "Xác thực hai yếu tố.",
    "Password": "Mật khẩu",
    "SignUp": "Đăng ký",
    "Auth_LogIn": "Đăng nhập",
    "Auth_Register": "Đăng ký",
    "Account_LoginTitle": "Đăng nhập",
    "RememberMe": "Ghi nhớ đăng nhập",
    "ForgotPassword": "Quên mật khẩu?",
    "Account_RegisterTitle": "Đăng ký",
    "AcceptedTerms": "Tôi đồng ý với điều khoản và điều kiện",
    "Account_LogoutTitle": "Đăng xuất",
    "Account_LogoutClick": "Nhấn vào đây để đăng xuất",
    "Account_LogoutSuccess": "Bạn đã đăng xuất thành công.",
    "Account_LockoutTitle": "Tài khoản bị khóa",
    "Account_LockoutMessage": "Tài khoản này đã bị khóa. Vui lòng thử lại sau hoặc liên hệ bộ phận hỗ trợ.",
    "Error_Title": "Lỗi.",
    "Error_Message": "Đã xảy ra lỗi khi xử lý yêu cầu của bạn.",
    "RequestId": "Mã yêu cầu:",
    "LoadingPatients": "Đang tải bệnh nhân qua API...",
    "LoadingPrescriptions": "Đang tải đơn thuốc qua API...",
    "LoadingReports": "Đang tải báo cáo qua API...",
    "NoReportType": "Không có loại báo cáo",
    "ConfirmDeleteAppointment": "Xóa lịch hẹn này?",
    "ConfirmDeletePrescription": "Xóa đơn thuốc này?",
    "FailedAddPatient": "Không thể thêm bệnh nhân:",
    "FailedUpdatePatient": "Không thể cập nhật bệnh nhân:",
    "FailedLoadPatients": "Không thể tải danh sách bệnh nhân:",
    "FailedLoadPatient": "Không thể tải bệnh nhân:",
    "FailedAddAppointment": "Không thể thêm lịch hẹn:",
    "FailedUpdateAppointment": "Không thể cập nhật lịch hẹn:",
    "FailedDeleteAppointment": "Không thể xóa lịch hẹn:",
    "FailedLoadAppointment": "Không thể tải lịch hẹn:",
    "FailedLoadAppointments": "Không thể tải danh sách lịch hẹn:",
    "FailedAddPrescription": "Không thể thêm đơn thuốc:",
    "FailedUpdatePrescription": "Không thể cập nhật đơn thuốc:",
    "FailedDeletePrescription": "Không thể xóa đơn thuốc:",
    "FailedLoadPrescriptions": "Không thể tải danh sách đơn thuốc:",
    "FailedLoadReports": "Không thể tải báo cáo:",
    "InvalidCredentials": "Thông tin đăng nhập không hợp lệ, vui lòng thử lại!",
    "AcceptTermsRequired": "Vui lòng chấp nhận điều khoản và điều kiện.",
    "CouldNotCreateReport": "Không thể tạo báo cáo.",
    "EnterReportTypeName": "Vui lòng nhập tên loại báo cáo trước khi lưu làm mẫu.",
    "ReportTypeExists": "Mẫu loại báo cáo này đã tồn tại.",
    "CouldNotCreateReportType": "Không thể tạo loại báo cáo.",
    "InvalidFileName": "Vui lòng nhập tên tệp hợp lệ!",
}


def write_resx(path: Path, data: dict) -> None:
    lines = [HEADER]
    for key, value in data.items():
        escaped = (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
        lines.append(f'  <data name="{key}" xml:space="preserve">')
        lines.append(f"    <value>{escaped}</value>")
        lines.append("  </data>")
    lines.append("</root>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1] / "Resources"
    write_resx(root / "SharedResources.resx", EN)
    write_resx(root / "SharedResources.vi.resx", VI)
    print(f"Wrote {len(EN)} keys")
